// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMwHt6x7e5N3SuohqFIXMN2ar5q0FTtBw',
    appId: '1:964927410610:web:bc5695d853cb1bcc9994ab',
    messagingSenderId: '964927410610',
    projectId: 'learningfirebase-a4097',
    authDomain: 'learningfirebase-a4097.firebaseapp.com',
    storageBucket: 'learningfirebase-a4097.appspot.com',
    measurementId: 'G-DHP17TLX3C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHJAcSp4A2gT87lisMcaaEkXOsSXvg-t4',
    appId: '1:964927410610:android:4952675393d703569994ab',
    messagingSenderId: '964927410610',
    projectId: 'learningfirebase-a4097',
    storageBucket: 'learningfirebase-a4097.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA10NVjbXCGhfO2ESfoOjc0CTX59qxr2sc',
    appId: '1:964927410610:ios:a46a339b9aeed4e49994ab',
    messagingSenderId: '964927410610',
    projectId: 'learningfirebase-a4097',
    storageBucket: 'learningfirebase-a4097.appspot.com',
    iosClientId: '964927410610-51qnn89v1g6ii9tsevatsm4211dt7jp0.apps.googleusercontent.com',
    iosBundleId: 'com.example.workWithFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA10NVjbXCGhfO2ESfoOjc0CTX59qxr2sc',
    appId: '1:964927410610:ios:a46a339b9aeed4e49994ab',
    messagingSenderId: '964927410610',
    projectId: 'learningfirebase-a4097',
    storageBucket: 'learningfirebase-a4097.appspot.com',
    iosClientId: '964927410610-51qnn89v1g6ii9tsevatsm4211dt7jp0.apps.googleusercontent.com',
    iosBundleId: 'com.example.workWithFirebase',
  );
}
